### ISSUE TITLE
[Fix] Adjust Initial Setup Screens

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#109]
### 📝 작업 목적
- 초기 세팅 화면의 몇가지 수정을 적용합니다.
---

### 🛠️ Tasks

* [x] 키보드 병아리 말고 다른 곳 눌러도 내려오게
* [x] 스크린타임 허용 뷰 글자 행간 조절
* [x] InitialTimeSettingView 생성 후, 수정
* [x] 메인에 백버튼 없애기(NavigationLink 없애기)
