### ISSUE TITLE
[Fix] SettingView 및 TimeSettingView 디자인 및 기능 수정

### ISSUE THREAD

**Issue by yejink0328** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#111]
### 📝 작업 목적

SettingView 및 TimeSettingView의 디자인 및 기능을 수정합니다.

---

### 🛠️ Tasks

[SettingView]
* [x] 키보드 바깥 터치해도 변경된 이름이 적용되게 하기 (키보드 return 눌렀을 때와 같이)
* [x] 시간 설정의 테두리가 잘리는 현상 해결하기

[TimeSettingView]
* [x] 설정 - 시간설정 부분에서 결정 버튼 수정
* [x] 시간설정에 x버튼 추가
* [x] 시간설정 백버튼 Chevron 으로 수정 (옷장뷰처럼 만들기)
