### ISSUE TITLE
[Fix] MainView, MainActivityView 디자인 및 기능 수정

### ISSUE THREAD

**Issue by dtd1232** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#118]
### 📝 작업 목적

MainView, MainActivityView 디자인 및 기능 수정

---

### 🛠️ Tasks

* [x] ~~Refresh Button 추가해서 MainActivityView 새로고침 할 수 있도록 하기~~
* [x] 병아리 움직임 들어가는 거
* [x] ~~메인 화면 모달에 x버튼 추가~~
* [x] 레벨 없애기
* [x] 바뀐 감정으로 걷는 애니메이션
* [x] ~~메인 화면 스킨 바뀌기->옷장에서 선택한거로 바꾸기~~ (issue#131)
* [x] 병아리 상호작용 이미지 .svg로 변환하기
