### ISSUE TITLE
[Fix] 달력 내부 다이어리 디자인 수정

### ISSUE THREAD

**Issue by chldudqlsdl** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#121]
### 📝 작업 목적

달력 내부의 다이어리 디자인을 수정합니다

---

### 🛠️ Tasks

* [ ] 사용시간 표출 형식 변경
* [ ] 병아리 크기 조정
* [ ] 노트 위치 조정
