### ISSUE TITLE
[Fix] MainView 병아리 움직임

### ISSUE THREAD

**Issue by chldudqlsdl** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#131]
### 📝 작업 목적

MainView에 걷는 병아리 감정 추가와 스킨 추가

---

### 🛠️ Tasks

* [ ] 병아리 움직임 들어가는 거
* [ ] 바뀐 감정으로 걷는 애니메이션
* [ ] 메인 화면 스킨 바뀌기->옷장에서 선택한거로 바꾸기
