### ISSUE TITLE
[Refactor] Device Activity Extension(FeedBack)

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#29]
### 📝 작업 목적
- #24 후속
- 애플의 보안정책에 따라, 주요 로직이 Extension 내부에 위치하는 사유로, 변경된 디자인 패턴을 프로젝트 구조에 적용합니다.
- 공통 코드 모듈은 별도의 프레임워크로 분리하지 않는 것이 일반적이지만, 현재의 애플의 보안정책에 따라 DeviceActivityReport Extension으로 인한 제한사항을 고려할 때, **공통 코드 모듈**  즉,특정 UI 컴포넌트를 포함한 여러 코드를(Theme, Component, Extensions, Utils) 공유 프레임워크에 포함하는 것이 필요하다고 판단했습니다. 자세한 이유는 다음과 같습니다.

> - 메인 앱에서 DeviceActivityReport로 데이터를 전달하는 것은 가능하지만, 애플의 보안 정책으로 인해 반대의 전달은 불가능합니다. 따라서, 메인 앱과 Extension 모두에서 사용되는 공통 코드 모듈을 공유 프레임워크로 구성하면, 제한적이지만 한 방향으로(App to Extension) 접근 및 사용이 가능하게 됩니다.
> - 이러한 이유로, 공통 코드 모듈을 공유 프레임워크인 'PeepPeepCommons'에 포함시키는 작업을 진행하려 합니다. (코드의 중복을 최소화하고, 메인 앱과 Extension간의 일관성을 유지하려는 목적입니다.)
> - 에셋 카탈로그도 같은 이유로 , 메인 앱과 Extension간 모두에서 활용될 수 있게끔 작업합니다.
---

### 🛠️ Tasks

* [x] Shard FrameWork를 사용해, 메인 앱과 Extension 간, 코드 공유
     * [x] 공유하려는 코드 (Theme, Common Components 등)를 새 Framework로 이동
     * [x] 메인 앱과 Extension의 타겟에 생성한 Framework 추가
* [x] Shared Asset Catalog를 생성해, 메인 앱과 Extension 간, 에셋 공유
     * [x] 공유하려는 에셋을 새 Asset Catalog에 추가
     * [x]  메인 앱과 Extension의 Build Phases에 새로운 Asset Catalog 추가
     
### 후속작업
* [x] AppGroup을 설정해 메인 앱과 Extension 간, 데이터 공유 ~~(CoreData)~~
     * [x] AppGroup 설정
     ~~* [ ] Shared Data를 AppGroup으로 저장하고 불러오는 로직 구현~~
