### ISSUE TITLE
[Feat] Implement InitialSetup

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#32]
### 📝 작업 목적
- 초기 세팅을 구현합니다. 총 4개의 설정 화면이 있으며, 각 화면을 지날 때마다 정보를 입력받고 사용시간 정보를 보여주는 등의 액션이 포함되 있으며, 상단의 프로그래스 바가 증가하여 사용자에게 설정 진행 상태를 표시해 줍니다.
  각 단계는 다음과 같습니다.

> - **1단계: 병아리 이름 설정**
> 사용자는 앱에서 관리할 병아리의 이름을 설정할 수 있습니다.
> - **2단계: 스마트폰 사용시간을 추적할 앱 선택**
> 사용자는 스마트폰 사용시간을 추적할 앱을 선택할 수 있습니다. 기본적으로 사용자의 스마트폰 사용 패턴을 분석하여 필요한 데이터를 제공하는데 사용됩니다.
> - **3단계: 스마트폰 사용시간 리포트 뷰**
> 사용자는 선택한 앱들의 휴대폰 사용시간 리포트를 확인할 수 있습니다. 이 리포트는 사용자가 앱을 얼마나 사용했는지의 정보를 제공합니다.
> - **~~4단계: 스마트폰 목표 사용시간 설정~~**
> ~~사용자는 일일 스마트폰 사용 목표 시간을 설정할 수 있습니다. 이 설정은 사용자가 스마트폰을 얼마나 자제해야 하는지의 기준을 제공합니다.~~

---

### 🛠️ Tasks

* [x] 모델 및 뷰모델 구현
    * [x] 뷰에 필요한 모델 설계 및 구현
    * [x] 뷰모델 설계 및 구현
    * [x] 뷰와 뷰모델 바인딩 설정
* [x] 병아리 네이밍 화면 구현
    * [x]  사용자 입력 필드 구현
* [x] 스마폰 사용 앱 선택 화면 구현
     * [x] 앱 리스트 표시 기능 구현
     * [x] 앱 선택 및 정보 저장 기능 구현
     * [x] 디바이스 액티비티 리포트 뷰 구현
* [x] 앱 사용 데이터 기반 리포트 화면 구현
     * [x] 데이터 시각화 기능 구현
~~사용시간 설정 필드 구현~~
~~설정 시간 저장 및 앱 사용에 반영 기능 구현~~ 
* [x]  단계별 진행 상황 표시 기능(프로그래스 바) 구현
* [x]  네비게이션 연결
    * [x]  스킵 버튼과 확인 버튼에 해당하는 플로우에 맞는 네비게이션을 구현

**Comment by hhajime** [comment]
* 스크린타임 로딩과정에서 오래 걸리는 경우를 대비해, Circular Progress 추가 소요가 있습니다.
* FamilyActivityPicker의 취소, 완료 버튼이 흰색으로 보이는 버그가 존재합니다.
