### ISSUE TITLE
[Feat] SplashView 구현

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#33]
### 📝 작업 목적

스토리를 보여주기 위한 SplashView를 구현합니다.

---

### 🛠️ Tasks

* [x] 스토리 텍스트
* [x] 스토리 이미지
* [x] 인디케이터 표시
* [x] 오른쪽에서 왼쪽으로 스와이프 하면 다음 화면으로 넘어가기
* [x] 왼쪽에서 오른쪽으로 스와이프 하면 이전 화면으로 넘어가기
* [ ] 다음 버튼 만들기
* [ ] 버튼 누르면 초기세팅 화면으로 넘어가기
