### ISSUE TITLE
[Feat] CostumeBook 기본 View 구현

### ISSUE THREAD

**Issue by yejink0328** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#44]
### 📝 작업 목적

CostumeBook의 기본 View 코드를 구현

---

### 🛠️ Tasks

* [x] Costume의 2 X N 배열

* Costume의 각 요소 구현
   - [x] 이미지
   - [x] 이름
   - [x] 선택 표시
   
* [x] 각 요소 클릭 시  Bottom Sheet 올라오게 하기
* [x] Bottom Sheet에 나가기 버튼 구현
* Bottom Sheet에 Costume 각 요소 구현
   - [x] 이미지
   - [x] 이름
   - [x] 선택 표시
   
* [x] Costume 해금 조건 달성 여부에 따라 이미지 바뀌기
