### ISSUE TITLE
[Feat] SettingView를 만듭니다.

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#46]
### 📝 작업 목적

SettingView 파일 만들기
설정 화면을 위한 SettingView 구현

---

### 🛠️ Tasks

* [ ] SettingView 파일 만들기
* [ ] MainView 연결
* [ ] 이름 입력창 구현(텍스트 필드)
* [ ] 시간설정 누르면 바텀시트 올라오게 하기
