### ISSUE TITLE
[Feat] Loading화면을 구현합니다.

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#49]
### 📝 작업 목적

로딩 화면 구현

---

### 🛠️ Tasks

* [ ] 병아리 아이콘 이미지 넣기
* [ ] 로고 타이포 이미지 넣기
* [ ] SplashView로 자연스럽게 넘어가기
