### ISSUE TITLE
[Feat] 사용자-병아리 상호작용 구현

### ISSUE THREAD

**Issue by dtd1232** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#65]
### 📝 작업 목적

사용자가 터치하는 곳으로 병아리가 따라가는 상호작용을 구현합니다.

---

### 🛠️ Tasks

* [ ] 사용자의 터치 위치로 병아리 위치 이동
  * [ ] 프레임 수 조절
  * [ ] 프레임별로 다른 이미지 나오게 하기
* [ ] MainView에서 노출되는 View 크기 조절
