### ISSUE TITLE
[Feat] Goaltime Auto Selection, App Download Date Save

### ISSUE THREAD

**Issue by chldudqlsdl** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#66]
## 📝 작업 목적

- GoalTimeAutoSelection : 현재는 유저가 당일 목표시간을 선택하지 않은 상태라면 기본값을 설정해놓고 가져오는 상황인데, 이를 당일 이전 가장 최근에 목표시간을 설정한 날의 목표시간을 가져오도록 한다.
- AppDownloadDateSave : 달력에서 앱을 다운 받기 이전의 날짜를 클릭하면 현재는 더미목표시간으로 달성률을 계산해준다. 하지만 이는 사용자의 몰입감을 떨어뜨리고, 혼란을 줄 수 있다.(앱을 다운 받기 전인데 병아리 스트레스지수가 왜있지?) 달력에서 다운 받기 이전 날짜를 클릭하면 성장일지에 데이터를 보여주지 않도록 한다.

---

### 🛠️ Tasks
- GoalTimeAutoSelection
* [x] 당일의 목표설정시간이 없다면, 그 날 이전의 가장 최근 목표시간을 가져오기

- AppDownloadDateSave
* [x] 앱이 다운로드 된 날을 유저디폴트에 저장한다
* [x] 달력에서 앱이 다운로드 된 날 이전의 날짜를 클릭하면 스트레스 지수를 보여주지 않도록 구현한다
