### ISSUE TITLE
[Feat] MainView와 MainActivityView를 수정합니다.

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#77]
### 📝 작업 목적

바뀐 디자인을 반영하기 위해 MainActivityView와 MainView를 수정합니다.
ZStack으로 정확한 위치에 버튼을 만들어야 해서 MainActivityView를 수정합니다.

---

### 🛠️ Tasks

* [x] 스트레스 지수 Rectangle 맞추기
* [x] 사용 시간 터치하면 앱 통계 화면 시트 올라오게 하기
* [x] 스트레스 지수 텍스트나 게이지바를 터치하면 스트레스 지수 설명이 시트로 올라오게 하기
* [x] 레벨 위치 맞추기
* [x] 레벨 설명 뷰 만들기
* [x] 레벨 터치하면 레벨 설명이 바텀시트로 올라오게 하기
