### ISSUE TITLE
[Feat] Implement CostumeBook Logic

### ISSUE THREAD

**Issue by chldudqlsdl** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#84]
### 📝 작업 목적

CostumeBookView(이하 도감) 에서 특정 코스튬을 클릭했을 때 이를 메인화면에 반영시킨다

---

### 🛠️ Tasks

* [ ] 익스텐션 내에서 UserDefaults에 dailyRecord 라는 키의 저장소를 만들고, 다운로드 날부터 오늘 날까지 모든 날짜를 돌면서 목표 달성 여부를 Bool값으로 넣는다. 
* [ ] 익스텐션 내의 UserDefaults 에서 모든 코스튬을 키로 하는 Bool 값 저장소를 만든다.
* [ ] dailyRecord 배열을 돌면서 코스튬의 조건에 만족하면 코스튬의 UserDefaults 를 true로 바꿔준다 -> 이미 달성한 코스튬은 매번 검사하지 않아도 되도록
