### ISSUE TITLE
[Feat] 기본 작업 파일 생성

### ISSUE THREAD

**Issue by dtd1232** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#9]
### 📝 작업 목적

기본 작업 파일을 생성하고 기본 깃허브 워크플로우에 대해 익혀봅시다.

---

### 🛠️ Tasks

* [x] 이슈 등록을 완료합니다.
  * [x] 작업자, 라벨, 프로젝트를 추가해봅시다.
  * [x] 브랜치를 생성해 봅시다.
* [x] 작업 파일을 생성합니다.
  * [x] Xcode에서 이전에 분기한 브랜치로 이동해 봅시다.
  * [x] 해당 브랜치에서 할당된 뷰 파일을 생성하고 커밋을 완료합니다.
* [ ] PR 및 디벨롭 브랜치에 정상적으로 머지된 것을 확인해 봅시다.
