### ISSUE TITLE
[Feat] HelperView에서 스트레스 지수 보여주기

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#90]
### 📝 작업 목적

HelperView에서 실시간 반영되는 스트레스 지수를 볼 수 있게 합니다.
안 될 수도 있습니다..
병아리 가출에 대한 설명 추가
좀 더 직관적이고 이해가 쉬운 병아리 스트레스 지수 설명 화면을 만듭니다.

---

### 🛠️ Tasks

* [x] 병아리 가출 이미지 추가
* [x] 병아리 가출 조건 작성
* [x] 폰트 적용
* [x] MainActivityView에 스트레스 지수만 나오는 뷰 만들기
* [ ] HelperView에서 스트레스 지수만 나오는 뷰 볼 수 있게 하기
