### ISSUE TITLE
[Feat] SettingView 디자인 반영

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep#93]
### 📝 작업 목적

SettingView 디테일을 맞춥니다.

---

### 🛠️ Tasks

* [x] 이름 텍스트 위치 조정
* [x] 설정 텍스트 디자인 반영
* [ ] 키보드 바깥 터치하면 키보드 사라지게 하기
